version: '3.9'
services:
  #mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
    - mongo_db:/data/db
  #api
  api:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      API_PORT: 3000
      DB_CONNECTION: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
  #frontend
  vue:
    build: ./frontend
    ports:
      - 8080:8080
    environment:
      VUE_APP_DB_URI: http://api:3000
    depends_on:
      - api

volumes:
  mongo_db: {}
