services:
  #mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
    - mongo_db:/data/db
  
  #api+frontend service
  api:
    build: .
    ports:
      - 8080:8080
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
